#!/usr/bin/perl -w

$^I = ".bak";

my $ppfile = "$ARGV[0]/manifests/init.pp";
pop @ARGV;
push @ARGV, $ppfile;

while (<>) {

  # Expand tabs
  s/\t/        /g;

  # Only double-quote strings when there's variable expansion.
  #   "foobarmumble" ->
  #       'foobarmumble'
  s("([^\$"]*)")('$1')g;

  # Variables should be braced when
  #    the variable is inside a double-quoted string"
  #  "this is $foo.bar" ->
  #    "this is ${foo}.bar"
  s/(".*\$)(\w+)(.*")/$1\{$2\}$3/;

  # File modes must be quoted and in octal
  #    mode => 644, ->
  #        mode => '0644',
  s/(mode\s*=>\s*)(\d+)\s*,/$1'$2',/;
  s/(mode\s*=>\s*)'(\d\d\d)',/$1'0$2',/;

  # Variable expansions are already strings. When alone, no need to quote.
  # Or brace, for that matter, which confuses puppet-lint
  #    "${foobar}" ->
  #        $foobar

  s/"\${(\w*)}"/\$$1/g;

  # use two-space tabs
  # a complete hack
  # sorry.
  s/    /  /g;

  print;
}
