#!/usr/bin/perl -w

$^I = ".bak";

while (<>) {
  s/"/'/g if (/".+"/ && !/".*\$.*"/);
  s/\t/        /g;
  s/(mode\s*=>\s*)(\d+)\s*,/$1'$2',/;
  s/(mode\s*=>\s*)'(\d\d\d)',/$1'0$2',/;
  s/"(\${\w*})"/$1/g;
  print;
}
