#!/bin/bash -eu

warn() { echo $* >&2; } 
die() { echo $* >&2; exit 1; } 

cd ${1:?"usage $(basename $0) modulename"}

if [ -d tests ]; then
  warn "Directory 'tests/' already exists, not creating."
  if cmp -s <(cd manifests; find .) <(cd tests; find .); then
    exit 0
  fi
  die "FATAL: 'tests/' and 'manifests/' have different layout!"
fi

for d in $(find manifests -type d); do
  mkdir -p ${d/manifests/tests}
done

for f in $(find manifests -type f -name *.pp); do
  t=${f/manifests/tests}
  perl -lane 'if (s/^class\s*(\S*).*/include $1/) { s/{//; print;}'  $f > $t
  [ -s $t ] || rm -f $t
done

